version: '2'
services:
    jsample-app:
        image: jsample
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://jsample-postgresql:5432/jsample
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jsample-postgresql:
        extends:
            file: postgresql.yml
            service: jsample-postgresql
